support.html
Fixed one inconsistency on the support page of the website. While the chart said there was a difference in response time between plans for minimal business impacts, the FAQ said there wasn't any difference. I corrected the FAQ so that both of them say there is a distinction between plans.
=> [FIX] Website English Version

bots.md
link on bots page to bots docs was broken: [https://rocket.chat/bots]()
link now fixed.
=> Update broken link to bots Docs from bots pages

cloud.html, index.html
Fixed:
* Links to the plans
* Removed target blank on home page when going to /cloud
* Changed from dot notation to comma.
=> Fix cloud plan links

support.html
I was asked to make it clear that Cloud is not included for on-premises clients. I have re-worded the support table and added a Cloud Support section in the FAQ type section at the bottom of the page.
=> Clarify meaning of basic support plan

partners.html
They must have been swapped with the new website.
=> Swap copy in Global Resellers and Technology Partners sections.

concession.html, press.html
Add illustration to Concession page:
Same as Press one but Concession is not linked to, and is not very visible. Very compatible in terms of illustration subject. 
Minor copy edits to the page too, and styling of page + illustration.
=> Add illustration to concession page + copy edits

index.html
The current heading "Blockchain" on the front page implies that the software's backend uses blockchain technology. This PR removes that bad implication and replaces it with a more honest yet appealing heading.
It also lengthens the second heading next to it to keep the headings symmetrical (for style).
**Before**
**After**
=> Remove implication that the Rocket.Chat software is built onto the blockchain

_layouts/en/default.html
If you go to the webnars page from the footer link you will see a white screen redirecting to the actual page. Removing the slash at the end of the link fixes this.
=> Stop redirecting to webnar pages

marketplace.html, marketplace.js
Fix #415 
Every time a user clicks on a category the url will be changed (this will not cause a refresh). Then we'll be able to share this url and the apps will be filtered accordingly.
=> Setting category on a url query parameter when clicking on it

_config.yml, _data/team.yml, _sass/pages/team.scss, _sass/ui/variables.scss, team.html
closes #459 
This fixes the broken about us element, and updates the team list.
Before:
After:
=> [FIX] Update team page

_sass/components/footer.scss
Look at `Star or fork on GitHub` buttons
Before:
After:
=> Fix GitHub buttons vertical align

blog/index.html
This change was requested in #507
closes #507
Before: 
After: 
>Note: I've not changed the events dates, only did that in the screenshots for a better view
=> [NEW] Use preview with images for events

_config.yml, main.js
Apparently most of the site uses a very subtle parallax effect on their backgrounds, the new pricing page broke that. This PR simply adds this effect back to it
=> [FIX] Add parallax effect back to pricing page

_data/install.yml
Version 2.14.1: https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.14.1
=> Bump desktop app version

_data/pricing.yml
Since we don't have a clear explanation or schedule for different types of updates, it's best to remove this information from the pricing page for now to avoid confusion.
=> Remove "Updates" from pricing page

_sass/pages/press.scss, press.html
Fixing font color on press page _Logos and Assets area_
Changing from dark to white "Fixes #613" "Closes #643"
@rafaelks check to confirm.
@MartinSchoeler Here is the fixed PR.
=> Press page font color fixed

README.md
Brief info added in README.md on starting rocketchat.github.io locally.
`Closes #657 `
=> Info on running project locally provided :tada:

legal/cloud/terms.md
Clarified the clause for data ownership. Rather than claiming ownership, user grants a license to operate and improve the service. Users retain ownership over the data they have submitted.
=> Clarification on data ownership / license grant

legal/cloud/terms.md
Removed legacy verbiage which should have been deleted by the last PR, now clarifying data ownership of user
=> Remove legacy verbiage

_sass/pages/home.scss
As seen before it stretches.
After edit, we have a better display with no stretch or shrink
"Closes: #414" "Closes: #680 "  @MartinSchoeler verify to confirm.
=> Scaling home-hero-image to not shrink or stretch

_includes/livechat.html
Update the Livechat script, removing `1.0.0` from the public path.
The Widget is not working properly on Rocket.Chat website.
=> [FIX] Update Livechat script
