RocketChat/rocketchat.github.io

blog/index.html

Add page links

---

_includes/mailchimp.html
_layouts/post.html
_sass/includes/mailchimp.scss
_sass/layouts/post.scss
blog/index.html
styles.scss

@engelgabriel could you re-enable our Mailchimp account before merging please.
Added to the top of blog post list and the bottom of each post.

Add Mailchimp

---

pt/community.html
pt/index.html
pt/support.html
pt/team.html

Here are some fixes to the Portuguese version of the website. Most of them include grammar and cohesiveness. There is one fix, however, that makes changes to content (the Support one),

[FIX] Website Portuguese Translation

---

_data/team.yml

Just updating my own position info within sales team

Update Dorgam position info

---

_sass/team.scss
team.html

Add team map

---

_config.yml
_sass/index.scss
index.html

Trial button to signup, add GitHub buttons

---

_sass/index.scss
index.html

@isabellarussell please merge at the end of the day.

Remove MWC banner

---

team.html

Fix handbook link and remove WIP

---

_data/team.yml

Finally got around to this. Thanks for adding it!

Added myself to the Team page.

---

_posts/2018/02/2018-02-02-10-ways-to-install-rocket-chat.md

Cloudron reached out to us on Twitter asking us to add them to this post on ways to deploy Rocket.Chat

Added Cloudron to post

---

blog/index.html

Shorten the truncation for blog posts

---

.prettierignore
_includes/styleguide/buttons.html
_includes/styleguide/form.html
_includes/styleguide/typography.html
_layouts/styleguide.html
_posts/2017/01/2017-01-04-creating-facebook-of-stocks.md
_sass/buttons.scss
_sass/form.scss
_sass/grid.scss
_sass/reset.scss
_sass/typography.scss
_sass/variables.scss
styleguide.html
styles.scss

Hey @SeanPackham, how are you?
I've been working on the styleguide for the new site on the new branch that I called `reskin`, I think it's a good approach when we'll merge it on branch master. So in this PR you can review the:
- Typography;
- Form elements;
- Buttons;
Let me know if everything is good for you :)
Thanks

Reskin: Styleguide

---

_posts/2018/03/2018-03-01-open-source-higher-education.md

https://www.linkedin.com/feed/update/urn:li:activity:6380444956451962880 links to old url
url changed because of date correction here: #152

Add redirect to post shared on social media with old url

---

_posts/2017/01/2017-01-04-creating-facebook-of-stocks.md

Remove first heading so Jekyll uses the post copy as the snippet

---

_config.yml
_sass/index.scss
index.html

Added bot banner

---

_posts/2018/04/2018-04-18-rocket-chat-summit-2018.md

Added code to ensure Marcelo pic stays centred

Ensure margin is centred on summit photo

---

redhat.html

Add RedHat page redirecting to official redhat pdf

---

_includes/webrules.html
_layouts/default.html
_layouts/en/default.html
_layouts/post.html
_layouts/pt/default.html

adding AgileCRM webrules script to all pages will give us ability to track known users navigation through website.

Add agilecrm webrules tracking to all pages

---

_includes/webrules.html

removed push notifications popup and added pageview tracking code, with no popups =)

Pageview tracking

---

_sass/pages/install.scss

Fix Download Select Background

---

index.html

Fix UK to US eng.

---

_sass/ui/theme.scss

Fix partners page select background

---

_posts/2018/05/2018-05-11-cube-tech-fair.md

Edit typo on CUBE tech event

---

_layouts/en/legal.html

Fix gdpr link 'type'

---

become-partner.html
contact.html

fix(Forms): Update name attr

---

team.html

fix lack between the two last items

---

_sass/pages/home.scss

fix buttons mobile view

---

webinar-subscribed.html
webinars.html
webinars.ics

@diegodorgam please can you update the ics file? thanks!

Update Webinar page

---

_layouts/en/default.html
_sass/bots.scss
_sass/components/banner.scss
_sass/components/hero.scss
_sass/ui/form.scss
_sass/ui/grid.scss
_sass/ui/mixins.scss
_sass/ui/reset.scss
_sass/ui/table.scss
_sass/ui/theme.scss
concession.html

I'm not sure, but I think we are using spaces instead of tabs so I made few changes...
I removed `position: absolute` from banner to avoid overlaps and a lot of margins/padding to balance...
Changed some paddings (maybe you wont agree but I think make the things more easier)
I really dont like play with paddings margins positions absolutes, and I think its a small price to pay.

[FIX] concession page and some css

---

_data/team.yml

Rafael Specht team's page information

---

contact.html

#349 @marceloschmidt done! thanks!

Update contact page with new Br office address

---

support.html

#338 @marceloschmidt check this out and let me know if this is what you had in mind :) I think it works better, thanks for bringing it to my attention!

Clarify monthly/annual pricing

---

_data/team.yml

Please add me to the team page

Add lucia guevgeozian to team page

---

_posts/2016/09/2016-09-21-bossie-awards-2016-the-best-open-source-applications.md
_posts/2017/02/2017-02-17-call-to-community-google-cloud-next-2017.md
_posts/2017/05/2017-05-22-rocketchat-funds-more-students-to-take-part-in-google-summer-of-code.md
_posts/2017/05/2017-05-31-celebrate-with-us.md
_posts/2017/06/2017-06-08-rocket-blasts-in-san-jose.md
_posts/2017/07/2017-07-02-manish-kakoti-extending-communications-beyond-teams-with-rocketchat-federation.md
_posts/2017/07/2017-07-02-mrinal-dhar-developing-end-to-end-encryption-with-signal-protocol.md
_posts/2017/07/2017-07-02-pradeep-kumar-bridging-the-email-and-rocketchat-divide-with-personal-email-gateway.md
_posts/2017/07/2017-07-05-sachin-shinde-add-rocketchat-to-any-app-with-mobile-sdk.md
_posts/2017/07/2017-07-06-naman-gupta-smaller-faster-and-more-bandwidthefficient-client-with-pwa.md
_posts/2017/07/2017-07-30-karan-batra-automatic-channels-creation-in-rocketchat.md
_posts/2017/07/2017-07-30-lucas-woo-instant-iphone-chat-integration-with-live-chat-sdk.md
_posts/2017/10/2017-10-27-rocket-chat-wins-all-things-open-startup-competition.md
_posts/2018/04/2018-04-18-rocket-chat-summit-2018.md

Think this fixes Issue #387 !
Thanks for your help guys!

Move Events cat to second in line

---

webinar-subscribed.html
webinars.html

- Added recorded webinar to subscription page
- Added recorded webinar to subscribed page
- changed subscription tag to `webinar6`

Add recorded webinar to subsciption and subscribed pages

---

_sass/pages/landing.scss

Fixing zindex for app modal

---

_sass/pages/landing.scss
marketplace.html

Improvements to header color and hero background

---

_config.yml

This simply bumps the version and makes the site use the newest css an js

FIx broken css on site

---

_layouts/en/default.html

Remove trailing forward slash leading to 404 on redirect to Pricing

---

index.html

Linking to blog post for now @engelgabriel, currently working on Atlassian page, so when that is done, I will link the banner to that.

Add Atlassian banner with link to Migration post

---

pricing.html

Until pricing page/install page is adapted

Temporary: Change self-managed to support

---

_layouts/en/default.html

[FIX] Fixing blog posts header background color

---

_sass/pages/landing.scss
marketplace.html
marketplace.js

Adding a message when there is no apps on a list

---

blog/index.html

This should stop the blog page from redirecting

Add Permalink to blog page

---

_sass/pages/team.scss
team.html

Also added team photo
@ggazzo can you help with formatting the image? It should be the same format and layout as the CEO section on rocket.chat/press:

Add About Us section to Team page

---

_includes/pricing-table.html
_sass/components/pricing-table.scss
_sass/ui/buttons.scss
_sass/ui/table.scss
_sass/ui/typography.scss
pricing.html
styles.scss

New Prices and tables for Pricing page

---

_config.yml
_data/pricing.yml
_data/selfHosted.yml
_includes/pricing-table.html
_sass/components/hero.scss
_sass/pages/pricing.scss
_sass/ui/table.scss
_sass/ui/typography.scss
pricing.html

This adds the new self hosted table as well as applying the rest of the design.

[NEW] Finish Pricing page redesign

---

_sass/pages/pricing.scss
pricing.html

closes #468 
and fixes the prices header being in the wrong direction on chrome.

Pricing page fixes

---

_config.yml

This will make the website use the latest version of the css
amend for https://github.com/RocketChat/rocketchat.github.io/pull/469

bump site version

---

_config.yml
_sass/pages/pricing.scss

This removes the blue line after the hero image.

[FIX]Remove Blue Line from pricing page

---

_config.yml
_sass/pages/pricing.scss

Centralize the text on prices 

---

_config.yml
_data/pricing.yml
_data/selfHosted.yml
_includes/pricing-table.html
_sass/components/pricing-table.scss

This adds the ability to add links to the pricing tables
to add a link, simply add a `link` to the yml object.
this also adds better descriptions  in the yml files

[NEW] Links in pricing table

---

pricing.html

Resolves #466 check the Google Doc and resolve in PR directly if necessary @engelgabriel @geekgonecrazy Thanks

Update Pricing FAQs

---

pricing.html

Until it gets reworded and confirmed for Cloud and Self-Managed

Uptime guarantee FAQ removed

---

press.html

This goal has been achieved! So i'm removing it.

Remove mention of future marketplace on Press page

---

_config.yml
_sass/pages/pricing.scss

This fixes the white chunk on the start of the page on mobile views.

[FIX] Mobile header

---

pricing.html

Changes the "Pro" plan button from "Start Trial" to "Contact Us"

fix pricing button

---

_sass/components/card.scss

[NEW] Create better hover for blog thumbnails 

---

_config.yml
press.html

[FIX] Thumbnails in the press page

---

_sass/pages/team.scss
team.html

@LuluGO can you confirm placement? 😁 
@isabellarussell I couldn't put like germany because would hit edge of content and couldn't put regular because would collide with Brazil's box.  So put to the right.

Add Uruguay to map

---

_data/team.yml

Due to a git conflict, I ended up adding myself to the wrong position in the `team.yml` file.
Changing now to be the last one

Change Douglas Gubert order in team.yml

---

pricing.html

This fixes the pricing page footer disappearing on self managed section

[FIX] Pricing Footer

---

pricing.html

Update wording & formatting of billing FAQs

---

install.html

[FIX] Windows install

---

_config.yml
_sass/pages/pricing.scss
pricing.html

[NEW] Improve pricing page

---

_config.yml
_sass/ui/typography.scss

[FIX] Reduce Space in pricing cards

---

awsrocketchat.html

Descriptive walk-through of what is in the diagram.

Add architectural description for devops users

---

index.html

For email users on IRC,  this feature is not obvious

Mention major differentiating feature in-line

---

_data/team.yml

Changed team.yml, adding myself to the page!

Adding myself to the team page

---

_includes/livechat.html
_layouts/default.html

This PR adds the new Livechat to the website.
The widget will communicate with the Sales server.

Add Livechat back to the website

---

_includes/livechat.html

Reverts RocketChat/rocketchat.github.io#664

Revert "Add livechat community version on website"

---

marketplace.js

As the commit message states. Upgrades to the marketplace are nearing completion and with that comes the requirement to register one's workspace with cloud in order to access App downloads and eventually purchase Apps.

Removal of App Download Buttons

---

atlassian.html

"Closes: #669 "
Navigate to https://rocket.chat/atlassian and scroll to the bottom.
**Initially**
**To**

atlassian button style arranged

---

main.js

Hi, @MartinSchoeler! I re-opened the PR  [https://github.com/RocketChat/rocketchat.github.io/pull/671](https://github.com/RocketChat/rocketchat.github.io/pull/671) here to solve cla not signed problem. Could you review it for me? Thanks!

[BUG Fixes] Fix cannot read property 'style' of undefined problem 🐛

---

_posts/2019/05/2019-05-02-ucs-and-rocket-chat.md

There has been additional feedback from the teams at Rocket.Chat and
Univention. The update reflects those changes.

Updated the text according to cross feedback

---

_posts/2019/05/2019-05-02-ucs-and-rocket-chat.md

I made a mistake during copy & paste from the text document to my last pull request. This one fixes it. I'm sorry for this inconvenience.
@MartinSchoeler: It would be good to have it merged today, because we will mention the blog article in our newsletter tomorrow. Thank you very much.

Fix copy & paste error in introduction

---

legal/cloud/terms.md
legal/privacy.md

Changes to both privacy policy and terms of use.
ToU: had to create full section to Marketplace, and to modify other provisions accordingly
Privacy: create an addition to reference account data and marketplace data being collected via apps, changed to consent- or legitimate interest-based newsletter
Added section to include clarifications for cloud-offering privacy
Made several wording updates, e.g. keep a consistent wording of customer terms instead of jumping to user terms

Terms Update for Marketplace launch

---

_data/team.yml

My pic is missing for now :disappointed:

Adds Guilherme Cruz to team

---

_data/team.yml

Just noticed we had that property so setting it

Add Aaron twitter handle

---

_data/team.yml

I was grabbing my picture from the team page and noticed he was still there 😬

Remove Daniel Carboni from team page

---

_data/team.yml

Add Laura to team.yml

---

_data/team.yml

Photo and information to team.yml were added.

Add Karina Monarkh to team page. 

---

install.html

So we have direct links like:
- https://rocket.chat/install#server
- https://rocket.chat/install#mobile
- https://rocket.chat/install#desktop

Add id anchors to download sections

---

_data/team.yml

Laura's picture is available, but for some reason the config is duplicated and doesn't show it properly.
- Updated Laura picture's config.

Updates Laura's pic config

---

pricing.html

Add minimum users on cloud plans

---

_config.yml
_sass/pages/pricing.scss
main.js
pricing.html

[NEW] Changes to pricing page

---

_includes/pages/contact.html
_sass/pages/contact.scss

Makes text selection on contact page to copy address impossible.  With this text selection is possible again

Remove z-index that pulls contact info down too far for text selection

---

forms.js

Use the team url with github integration

Use new URL for mail contact form

---

_data/i18n-general.yml
_includes/components/banner.html

COVID webinar banner changes

---

_includes/pages/home.html

Added spacing before link

---

legal/privacy.md

privacy: summary, subprocessors, clarifications

---

_data/pricing.yml

- New items added;
- Updated existing items descriptions;

Update Omnichannel Pricing Page section

---

_posts/2020-04-22-rc-secure-platform.md

Mentioning rate made point less clear

Simplify backup line on saas post
